### ISSUE TITLE
Crashed on Destruction

### ISSUE THREAD

**Issue by Niconoko** [Hexagon-Studio/Keepers-of-the-Stones#116]
### Issue description

https://pastebin.com/Aw8XfR3H
All in this crashlog

### How to reproduce this issue?

Using a skill "Destruction Power"

### Minecraft Version

1.19.2 (Main)

### Mod Version

2.7.3 (Release)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MagicalAlexey/Keepers-of-the-Stones/issues' target='_blank'>is not already reported</a>

**Comment by MagicalAlexey** [comment]
The game crashes when using some spells #115
