### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Osl00** [Hexagon-Studio/Keepers-of-the-Stones#134]
### Issue description

At random, the game crashes.  The crash reports seem to indicate a problem with your mod and I haven't managed to solve the problem by myself. 

[crash-2023-01-02_18.26.07-server.txt](https://github.com/Hexagon-Studio/Keepers-of-the-Stones/files/10332869/crash-2023-01-02_18.26.07-server.txt)

[crash-2023-01-01_22.24.06-server.txt](https://github.com/Hexagon-Studio/Keepers-of-the-Stones/files/10332873/crash-2023-01-01_22.24.06-server.txt)

[crash-2023-01-01_21.33.58-server.txt](https://github.com/Hexagon-Studio/Keepers-of-the-Stones/files/10332875/crash-2023-01-01_21.33.58-server.txt)

### How to reproduce this issue?

play normaly till it happen

### Minecraft Version

1.19.2 (Main)

### Mod Version

2.9.3 (Release)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MagicalAlexey/Keepers-of-the-Stones/issues' target='_blank'>is not already reported</a>

**Comment by MagicalAlexey** [comment]
Resolved in #133
