### ISSUE TITLE
Can't open on MCreator

### ISSUE THREAD

**Issue by ziolkoplays** [Hexagon-Studio/Keepers-of-the-Stones#139]
### Issue description

When I try to open this mod on MCreator it says I need to update to the version it was made on but I'm on the newest version(This is not to reupload your mod; im trying to create an addon and wont upload it.)

### How to reproduce this issue?

![Screenshot 2023-06-17 201723](https://github.com/Hexagon-Studio/Keepers-of-the-Stones/assets/124638625/1df514dc-e3c6-48bc-bd50-ea79924e9429)

### Minecraft Version

1.19.2 (Main)

### Mod Version

2.9.3 (Release)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MagicalAlexey/Keepers-of-the-Stones/issues' target='_blank'>is not already reported</a>

**Comment by ziolkoplays** [comment]
Woops wrong image

**Comment by ziolkoplays** [comment]
new image 
![Screenshot 2023-06-17 201723](https://github.com/Hexagon-Studio/Keepers-of-the-Stones/assets/124638625/00f626bb-8543-4f6f-8304-402b16f72c1c)

**Comment by MagicalAlexey** [comment]
We use the developer version for development.

**Comment by ziolkoplays** [comment]
OHHH thanks!

**Comment by ziolkoplays** [comment]
Wait; How do you get to that?
