### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Hrumer** [Hexagon-Studio/Keepers-of-the-Stones#91]
### Issue description

When using the "point" item, the teleportation wizard's server crumbles

### How to reproduce this issue?

I decided to teleport to a checkpoint that is in another dimension and the server is crashing

### Minecraft Version

1.18.2 (Main)

### Mod Version

2.5.1 (Release)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MagicalAlexey/Keepers-of-the-Stones/issues' target='_blank'>is not already reported</a>

**Comment by MagicalAlexey** [comment]
Please write bug reports in English next time
